from . import settings as base

DEBUG = True
ALLOWED_HOSTS = [*getattr(base, "ALLOWED_HOSTS", []), "localhost"]

# Reexportá lo necesario:
SECRET_KEY = base.SECRET_KEY
INSTALLED_APPS = base.INSTALLED_APPS
MIDDLEWARE = base.MIDDLEWARE
TEMPLATES = base.TEMPLATES
DATABASES = base.DATABASES

SECURE_SSL_REDIRECT = False
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_PRELOAD = False
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
