# Generated by Django 5.2.5 on 2025-09-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academia_horarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="horarioclase",
            name="docentes",
        ),
    ]
